#!/bin/bash

make clean
clear
make
echo "Choose method of sorting: bubble-sort, lib-qsort or custom-qsort:"
read mode
if [ "$mode" = "bubble-sort" ] || [ "$mode" = "lib-qsort" ] || [ "$mode" = "custom-qsort" ];
then
./build/ss $mode > log_eblan.log
else
echo "Error method of sorting"
fi

